### ISSUE TITLE
problem converting annotations to png

### ISSUE THREAD

**Issue by anupamaray** [anderskm/tucgffcnnfss#1]
Hi,

At step 1 of guide 3, main_writeLabels2PNG.m is writing black png files. Could you suggest some solution.

Thanks,
Anupama

**Comment by anderskm** [comment]
Hi Anupama,

How are you viewing the generated png-files?
Some png-viewers such as Windows Photo Viewer shows the images as black, although they are correctly saved. I think this is because the pixel images are saved as integers from 0 to 256, but the labels are generally very low value starting from 0 to the number of labels.

Have you tried displaying the images in Matlab prior to writing them?
You can add the following lines at line 65 in the script to display the images as they are written:

```
figure(1);
clf;
imagesc(RelabelMap);
axis image;
drawnow;
```

If they appear correct, they should also be saved correct.

Cheers,
Anders

**Comment by anupamaray** [comment]
Thanks Anders for such a wonderful step by step guide.. 
Now it is displaying correctly in MATLAB.. 
But the LMDBs created are having max channel intensity of 10 in my case.. any pointers to this ..

Thanks for your time and help

**Comment by anupamaray** [comment]
Thanks Anders for such a wonderful step by step guide.. 
Now it is displaying correctly in MATLAB.. 
But the LMDBs created are having max channel intensity of 10 in my case.. any pointers to this ..

Thanks for your time and help

**Comment by anderskm** [comment]
The max channel intensity of the labels LMDB should correspond to the max label index of your dataset. E.g. if you have 10 different classes (excluding unknown), it should display 10.
If you are using Pascal it should display 59 as the max intensity, however, if you are using another dataset it will most likely differ.
What dataset are you using? Pascal or a different one?

**Comment by anupamaray** [comment]
I am just trying to replicate your results with Pascal Context dataset for a hands-on.

**Comment by anderskm** [comment]
I have looked into it. It appears that there is a minor error in the script: main_writeLabels2PNG.m.
Line 27 should say

`selectMapping = 2;`

rather than

`selectMapping = 4;`

It changes the mapping of the labels to PASCAL Context 59, which is used in the guide.
My apologies :-)

**Comment by anupamaray** [comment]
Thanks Anders.. its showing 59 now

**Comment by anderskm** [comment]
Everything seems to be sorted out, so I'm closing this issue.
